{
    "name": "Steps - Productores",
    "summary": "Productores, fundos, estimaciones, tarifas y liquidaciones",
    "version": "18.0.1.8.0",
    "category": "Agriculture",
    "author": "Steps Consulting",
    "license": "LGPL-3",
    "depends": ["step_hr", "step_management_costs", "step_packing", "step_inventory_fruit_tag", "purchase", "account", "analytic"],
    "data": [
        "security/producer_core_rules.xml",
        "security/producer_rules.xml",
        "security/ir.model.access.csv",
        "data/contract_sequence.xml",
        "data/estimate_stage.xml",
        "data/producer_sequences.xml",
        "views/step_export_grower_discount_views.xml",
        "views/step_export_grower_rate_views.xml",
        "views/step_export_grower_discount_tag_views.xml",
        "views/step_export_grower_rate_tag_views.xml",
        "views/step_export_estimate_tag_views.xml",
        "views/step_export_estimate_stage_views.xml",
        "views/step_export_estimate_views.xml",
        "views/step_export_producer_estimate_views.xml",
        "views/producer_settlement_views.xml",
        "report/producer_settlement_report.xml",
        "views/producer_accounting_views.xml",
        "views/producer_dashboard.xml",
        "views/producer_partner_views.xml",
        "views/producer_contract_views.xml",
        "views/purchase_order_views.xml",
        "views/preliquidation_price_views.xml",
        "views/grower_tariff_views.xml",
        "views/menu.xml",
        "data/legacy_aliases.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "step_producers/static/src/js/dashboard.js",
            "step_producers/static/src/xml/dashboard.xml",
        ],
    },
    "application": True,
    "installable": True,
}
