{
    "name": "Steps - Gestión y Costos",
    "summary": "Presupuestos agrícolas por hectárea, planificación y control de costos",
    "version": "18.0.20.0.0",
    "author": "Steps Consulting",
    "category": "Operations/Planning",
    "license": "LGPL-3",
    "depends": ["base", "mail", "web", "account", "product", "stock", "purchase"],
    "data": [
        "security/management_security.xml",
        "security/ir.model.access.csv",
        "data/management_sequences.xml",
        "data/estimation_data.xml",
        "data/historical_template_versions.xml",
        "views/cost_center_views.xml",
        "views/budget_group_views.xml",
        "views/exchange_rate_views.xml",
        "views/budget_template_views.xml",
        "views/operational_budget_views.xml",
        "views/budget_import_views.xml",
        "views/product_views.xml",
        "views/estimation_curve_views.xml",
        "views/estimation_views.xml",
        "views/estimation_import_views.xml",
        "views/planning_views.xml",
        "views/harvest_plan_views.xml",
        "views/crop_program_views.xml",
        "views/crop_program_import_views.xml",
        "views/stock_requirement_views.xml",
        "views/historical_cost_views.xml",
        "views/historical_import_views.xml",
        "views/management_dashboard_views.xml",
        "views/production_order_views.xml",
        "views/production_order_report.xml",
        "wizard/budget_reopen_views.xml",
        "wizard/budget_variance_views.xml",
        "wizard/plan_weekly_preview_views.xml",
        "wizard/production_order_preview_views.xml",
        "wizard/season_comparison_views.xml",
        "wizard/out_of_op_classifier_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "step_management_costs/static/src/js/management_dashboard.js",
            "step_management_costs/static/src/xml/management_dashboard.xml",
            "step_management_costs/static/src/scss/management_dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
