# -*- coding: utf-8 -*-
{
    "name": "Steps - Exportaciones",
    "summary": "Programa comercial, embarques y liquidaciones de exportación Steps",
    "version": "18.0.2.9.5",
    "category": "Agriculture",
    "author": "Steps Consulting",
    "license": "LGPL-3",
    "depends": ["step_producers", "base", "mail", "step_hr", "step_management_costs", "step_packing", "step_inventory_fruit_tag", "step_dispatch_guide", "step_accounting_multicurrency", "sale", "mrp", "account", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "security/export_rules.xml",
        "data/sales_program_sequence.xml",
        "data/export_stage.xml",
        "data/operational_sequences.xml",
        "views/step_export_vessel_views.xml",
        "views/step_export_sale_mode_views.xml",
        "views/step_export_payment_concept_views.xml",
        "views/step_export_shipping_instruction_views.xml",
        "views/step_export_dispatch_order_views.xml",
        "views/step_export_customer_claim_views.xml",
        "views/step_export_stock_reservation_views.xml",
        "views/step_export_vessel_tag_views.xml",
        "views/step_export_sale_mode_tag_views.xml",
        "views/step_export_shipping_instruction_tag_views.xml",
        "views/step_export_export_tag_views.xml",
        "views/step_export_export_stage_views.xml",
        "views/step_export_export_views.xml",
        "views/step_export_master_views.xml",
        "views/step_export_accounting_config_views.xml",
        "views/step_export_sales_program_views.xml",
        "views/step_export_shipment_views.xml",
        "views/step_export_claim_views.xml",
        "views/step_export_settlement_views.xml",
        "views/step_export_exterior_expense_views.xml",
        "views/producer_settlement_integration_views.xml",
        "views/season_statement_views.xml",
        "report/season_statement_report.xml",
        "views/step_export_packaging_program_views.xml",
        "views/step_export_forecast_views.xml",
        "views/step_export_packing_list_views.xml",
        "views/step_export_receivables_views.xml",
        "report/packing_list_report.xml",
        "report/shipment_report.xml",
        "views/dashboard.xml",
        "views/navigation.xml",
        "views/menu.xml",
        "views/producer_integration_menu.xml",
        "data/producer_integration_aliases.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "step_export/static/src/js/dashboard.js",
            "step_export/static/src/xml/dashboard.xml",
            "step_export/static/src/scss/dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
