# -*- coding: utf-8 -*-
{
    "name": "Steps - Exportaciones",
    "summary": "Exportaciones, tarifas a productor y estimacion de cosecha "
                "(puerto desde Studio, ticket 33 Cerro El Plomo).",
    "version": "18.0.1.0.0",
    "category": "Agriculture",
    "author": "Steps Consulting",
    "license": "LGPL-3",
    "depends": ["base", "mail", "step_hr", "step_management_costs", "account"],
    "data": [
        "security/ir.model.access.csv",
        "views/step_export_vessel_views.xml",
        "views/step_export_sale_mode_views.xml",
        "views/step_export_payment_concept_views.xml",
        "views/step_export_grower_discount_views.xml",
        "views/step_export_grower_rate_views.xml",
        "views/step_export_shipping_instruction_views.xml",
        "views/step_export_dispatch_order_views.xml",
        "views/step_export_customer_claim_views.xml",
        "views/step_export_stock_reservation_views.xml",
        "views/step_export_vessel_tag_views.xml",
        "views/step_export_sale_mode_tag_views.xml",
        "views/step_export_grower_discount_tag_views.xml",
        "views/step_export_grower_rate_tag_views.xml",
        "views/step_export_shipping_instruction_tag_views.xml",
        "views/step_export_export_tag_views.xml",
        "views/step_export_estimate_tag_views.xml",
        "views/step_export_export_stage_views.xml",
        "views/step_export_estimate_stage_views.xml",
        "views/step_export_export_views.xml",
        "views/step_export_estimate_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
