# -*- coding: utf-8 -*-
{
    "name": "Steps - Exportaciones",
    "summary": "Exportaciones, tarifas a productor y estimacion de cosecha "
                "(puerto desde Studio, ticket 33 Cerro El Plomo).",
    "version": "18.0.2.3.0",
    "category": "Agriculture",
    "author": "Steps Consulting",
    "license": "LGPL-3",
    "depends": ["base", "mail", "step_hr", "step_management_costs", "step_packing", "step_inventory_fruit_tag", "step_dispatch_guide", "sale", "mrp", "account", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "security/export_rules.xml",
        "data/sales_program_sequence.xml",
        "data/estimate_stage.xml",
        "data/export_stage.xml",
        "data/operational_sequences.xml",
        "views/step_export_vessel_views.xml",
        "views/step_export_sale_mode_views.xml",
        "views/step_export_payment_concept_views.xml",
        "views/step_export_grower_discount_views.xml",
        "views/step_export_grower_rate_views.xml",
        "views/step_export_shipping_instruction_views.xml",
        "views/step_export_dispatch_order_views.xml",
        "views/step_export_customer_claim_views.xml",
        "views/step_export_stock_reservation_views.xml",
        "views/step_export_vessel_tag_views.xml",
        "views/step_export_sale_mode_tag_views.xml",
        "views/step_export_grower_discount_tag_views.xml",
        "views/step_export_grower_rate_tag_views.xml",
        "views/step_export_shipping_instruction_tag_views.xml",
        "views/step_export_export_tag_views.xml",
        "views/step_export_estimate_tag_views.xml",
        "views/step_export_export_stage_views.xml",
        "views/step_export_estimate_stage_views.xml",
        "views/step_export_export_views.xml",
        "views/step_export_estimate_views.xml",
        "views/step_export_producer_estimate_views.xml",
        "views/step_export_master_views.xml",
        "views/step_export_accounting_config_views.xml",
        "views/step_export_sales_program_views.xml",
        "views/step_export_shipment_views.xml",
        "views/step_export_claim_views.xml",
        "views/step_export_settlement_views.xml",
        "views/step_export_producer_settlement_views.xml",
        "views/step_export_packaging_program_views.xml",
        "views/step_export_forecast_views.xml",
        "views/step_export_packing_list_views.xml",
        "views/step_export_receivables_views.xml",
        "report/packing_list_report.xml",
        "report/shipment_report.xml",
        "views/dashboard.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "step_export/static/src/js/dashboard.js",
            "step_export/static/src/xml/dashboard.xml",
            "step_export/static/src/scss/dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
