# © 2025 (Jamie Escalante <jamie.escalante7@gmail.com>)
# -*- coding: utf-8 -*-
{
    'name': "Step Actividades",
    'summary': "",
    'description': """ Crea un campo de Alcance liquido con el monto a pagar en todos los recibos de nomina
    """,

    'author': "jamie.escalante7@gmail.com",
    'website': "",
    'category': 'HR',
    'version': '18.0',

    'depends': ['base',
                'hr_holidays_gantt',
                'hr_work_entry_holidays',
                'account',
                'hr_payroll',
                'hr_work_entry_contract_enterprise',
                'sale',
                'sale_management',
                'fleet'],
    'data': [
        'security/ir.model.access.csv',
        'security/history_security.xml',
        'data/ir_sequence.xml',
        'views/res_company_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_salary_custom_views.xml',
        'wizard/hr_input_step_wizard.xml',
        'wizard/hr_entry_xls_wizard.xml',
        'views/hr_route_views.xml',
        'views/step_temporada_views.xml',
        'views/step_fundo_views.xml',
        'views/step_especie_views.xml',
        'views/step_grupo_variedad_views.xml',
        'views/step_variedad_views.xml',
        'views/step_actividad_views.xml',
        'views/step_labor_views.xml',
        # 'views/step_cosecha_views.xml',
        'views/step_centro_costo_views.xml',
        'views/product_pricelist_views.xml',
        'views/project_task_views.xml',
        'views/step_tarja_views.xml',
        # 'views/step_tarja_cost_views.xml',
        'views/account_move_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_contract_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/step_tracker_views.xml',
        'views/step_movi_registry_views.xml',
        # 'views/step_cosecha_registry_views.xml',
        # 'views/step_cosecha_recepcion_views.xml',
        # 'views/step_cosecha_proceso_views.xml',
        'views/step_work_schedule_views.xml',
        'views/step_haber_costeo_views.xml',
        'views/hr_salary_custom_line.xml',
        'views/hr_salary_contract_line.xml',
        'views/step_tarja_cost_line_views.xml',
        'views/step_movi_registry_line_views.xml',
        'views/step_movi_cost_views.xml',
        'views/step_tarja_line_views.xml',
        'views/step_history_views.xml',
        'views/menu_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_sector_views.xml',
        'wizard/report_attendance_view.xml',
        'wizard/report_by_process_view.xml',
    ],
    'demo': [],
}
