"""Matriz campo Previred -> dato del motor SimpleDigital.

**Generada desde el codigo del generador vigente**, no deducida: cada entrada
guarda la expresion exacta de `PreviredExportController.download_previred_txt` que produce ese campo.

Es la evidencia de que ninguna correspondencia entre regla salarial y campo
oficial se adivino, y el punto de partida para conciliar importes contra
muestras existentes. Si el proveedor cambia su generador, esta matriz debe
regenerarse y las pruebas de conciliacion lo detectan.
"""

from odoo.addons.step_hr_previred.models.previred_adapter import FieldSource

#: `(posicion, tipo de origen, expresion del generador)`
RAW_MATRIX = [

    (1, 'computed', 'clean_rut[:-1] ;; "0" ;; "0"'),
    (2, 'computed', 'clean_rut[-1] ;; "0" ;; "0"'),
    (3, 'employee', "normalize_name_part(name_parts[1]) if len(name_parts) > 1 else ''"),
    (4, 'employee', "normalize_name_part(name_parts[2]) if len(name_parts) > 2 else ''"),
    (5, 'employee', "normalize_name_part(name_parts[0]) if len(name_parts) > 0 else ''"),
    (6, 'employee', "'M' if gender == 'male' else ('F' if gender == 'female' else 'M')"),
    (7, 'constant', "'0' if country and country.code == 'CL' else '1'"),
    (8, 'constant', "'01'"),
    (9, 'period', 'period_str'),
    (10, 'period', 'period_str'),
    (11, 'constant', "'AFP' ;; 'INP' ;; 'SIP' ;; 'AFP'"),
    (12, 'constant', "'0' ;; '2' if contract.pension_option == 'sip' else '1' ;; '3'"),
    (13, 'computed', 'self._get_real_worked_days_from_payslip(payslip)'),
    (14, 'constant', '"0"  # Línea principal siempre es "0"'),
    (15, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (16, 'unused', 'en blanco (uso futuro / no aplica)'),
    (17, 'unused', 'en blanco (uso futuro / no aplica)'),
    (18, 'computed', 'segment ;; "D" ;; "A" ;; "D"'),
    (19, 'contract', 'str(contract.family_simple_loads_count or 0)'),
    (20, 'contract', 'str(contract.family_maternal_loads_count or 0)'),
    (21, 'contract', 'str(contract.family_invalid_loads_count or 0)'),
    (22, 'computed', 'str(int(sum(asignacion_familiar_line.mapped(\'total\')))) if asignacion_familiar_line else "0"'),
    (23, 'unused', 'en blanco (uso futuro / no aplica)'),
    (24, 'unused', 'en blanco (uso futuro / no aplica)'),
    (25, 'constant', '"N"'),
    (26, 'computed', 'afp_code ;; "00"'),
    (27, 'rule', "0 ;; round(int(min(self._get_payslip_lines(payslip, rule_codes=['GROSS']) or 0, previred_indicator.tope_afiliados_afp or 0)))"),
    (28, 'rule', 'self._get_payslip_lines(payslip, rule_codes=[\'AFP\', \'AFP_EMP\']) or "0"'),
    (29, 'rule', 'self._get_payslip_lines(payslip, rule_codes=[\'SIS\']) or ""'),
    (30, 'computed', 'str(int(monto_cuenta2)) if monto_cuenta2 > 0 else ""'),
    (31, 'unused', 'en blanco (uso futuro / no aplica)'),
    (32, 'unused', 'en blanco (uso futuro / no aplica)'),
    (33, 'unused', 'en blanco (uso futuro / no aplica)'),
    (34, 'unused', 'en blanco (uso futuro / no aplica)'),
    (35, 'unused', 'en blanco (uso futuro / no aplica)'),
    (36, 'unused', 'en blanco (uso futuro / no aplica)'),
    (37, 'unused', 'en blanco (uso futuro / no aplica)'),
    (38, 'unused', 'en blanco (uso futuro / no aplica)'),
    (39, 'unused', 'en blanco (uso futuro / no aplica)'),
    (40, 'contract', 'contract.institucion_apvi_apvc or "" ;; ""'),
    (41, 'unused', 'en blanco (uso futuro / no aplica)'),
    (42, 'contract', 'contract.pay_format_apvi_apc or "" ;; ""'),
    (43, 'computed', 'f"{monto_apvi:08d}" if monto_apvi > 0 else "" ;; ""'),
    (44, 'unused', 'en blanco (uso futuro / no aplica)'),
    (45, 'contract', 'contract.institucion_apvi_apvc or "" ;; ""'),
    (46, 'unused', 'en blanco (uso futuro / no aplica)'),
    (47, 'contract', 'contract.pay_format_apvi_apc or "" ;; ""'),
    (48, 'computed', 'f"{monto_apvc_trabajador:08d}" if monto_apvc_trabajador > 0 else "" ;; ""'),
    (49, 'computed', 'f"{monto_apvc_empleador:08d}" if monto_apvc_empleador > 0 else "" ;; ""'),
    (50, 'unused', 'en blanco (uso futuro / no aplica)'),
    (51, 'unused', 'en blanco (uso futuro / no aplica)'),
    (52, 'unused', 'en blanco (uso futuro / no aplica)'),
    (53, 'unused', 'en blanco (uso futuro / no aplica)'),
    (54, 'unused', 'en blanco (uso futuro / no aplica)'),
    (55, 'constant', '"00"'),
    (56, 'unused', 'en blanco (uso futuro / no aplica)'),
    (57, 'unused', 'en blanco (uso futuro / no aplica)'),
    (58, 'unused', 'en blanco (uso futuro / no aplica)'),
    (59, 'unused', 'en blanco (uso futuro / no aplica)'),
    (60, 'unused', 'en blanco (uso futuro / no aplica)'),
    (61, 'unused', 'en blanco (uso futuro / no aplica)'),
    (62, 'unused', 'en blanco (uso futuro / no aplica)'),
    (63, 'unused', 'en blanco (uso futuro / no aplica)'),
    (64, 'rule', 'min(self._get_payslip_lines(payslip, rule_codes=[\'GROSS\']) or 0, previred_indicator.tope_afiliados_afp or 0) ;; ""'),
    (65, 'unused', 'en blanco (uso futuro / no aplica)'),
    (66, 'unused', 'en blanco (uso futuro / no aplica)'),
    (67, 'unused', 'en blanco (uso futuro / no aplica)'),
    (68, 'unused', 'en blanco (uso futuro / no aplica)'),
    (69, 'unused', 'en blanco (uso futuro / no aplica)'),
    (70, 'rule', 'min(self._get_payslip_lines(payslip, rule_codes=[\'GROSS\']) or 0, previred_indicator.tope_afiliados_afp or 0) * tasa_fonasa ;; int(round(cotizacion_fonasa)) ;; ""'),
    (71, 'rule', '"" ;; self._get_payslip_lines(payslip, [\'APORTE_MUTUAL\']) or 0'),
    (72, 'unused', 'en blanco (uso futuro / no aplica)'),
    (73, 'unused', 'en blanco (uso futuro / no aplica)'),
    (74, 'unused', 'en blanco (uso futuro / no aplica)'),
    (75, 'computed', 'health_code'),
    (76, 'constant', '"00000000"'),
    (77, 'constant', '"00000000" ;; round(int(min(self._get_payslip_lines(payslip, rule_codes=[\'GROSS\']), previred_indicator.tope_afiliados_afp or 0))) ;; ""'),
    (78, 'constant', '"1" ;; "2" ;; "1" ;; ""'),
    (79, 'constant', '"00000000" ;; f"{monto_clp:08d}" ;; f"{uf_valor:08.4f}".replace(\'.\', \',\') ;; "00000000" ;; ""'),
    (80, 'rule', '"00000000" ;; self._get_payslip_lines(payslip, [\'SALUD\']) or "" ;; ""'),
    (81, 'rule', '"00000000" ;; self._get_payslip_lines(payslip, [\'ISAPRE_EXTRA\']) or "" ;; ""'),
    (82, 'constant', '"00000000"'),
    (83, 'company', 'company.caja_compensacion or "" ;; company.caja_compensacion or ""'),
    (84, 'rule', 'min(self._get_payslip_lines(payslip, rule_codes=[\'GROSS\']) or 0, previred_indicator.tope_afiliados_afp or 0) ;; "00000000" ;; ""'),
    (85, 'rule', "self._get_payslip_lines(payslip, rule_codes=['CCAF_CREDITO']) or 0"),
    (86, 'unused', 'en blanco (uso futuro / no aplica)'),
    (87, 'computed', 'f"{int(total_ccaf_leasing):08d}" ;; ""'),
    (88, 'computed', 'f"{int(total_ccaf_seguro):08d}" ;; ""'),
    (89, 'unused', 'en blanco (uso futuro / no aplica)'),
    (90, 'computed', 'f"{cotizacion_ccaf_fonasa:08d}" ;; "00000000" ;; "00000000" ;; ""'),
    (91, 'unused', 'en blanco (uso futuro / no aplica)'),
    (92, 'period', '"0" ;; self._calculate_renta_imponible_last_month(employee, contract, period_dt)'),
    (93, 'constant', '"1" ;; "0"'),
    (94, 'computed', 'int(round(total_exp_vida)) ;; "0"'),
    (95, 'unused', 'en blanco (uso futuro / no aplica)'),
    (96, 'company', 'company.mutual ;; "00"'),
    (97, 'rule', "int(min(self._get_payslip_lines(payslip, rule_codes=['GROSS']), previred_indicator.tope_afiliados_afp) or 0)"),
    (98, 'rule', 'self._get_payslip_lines(payslip, [\'APORTE_MUTUAL\']) or 0 ;; ""'),
    (99, 'unused', 'en blanco (uso futuro / no aplica)'),
    (100, 'period', 'self._calculate_renta_imponible_last_month(employee, contract, period_dt) ;; renta_imponible(\'cesantia\') ;; str(renta_imponible_seguro_cesantia) ;; ""'),
    (101, 'rule', 'self._get_payslip_lines(payslip, [\'AFC_T\']) or ""'),
    (102, 'rule', 'self._get_payslip_lines(payslip, [\'AFC_EMPLEADOR\']) or ""'),
    (103, 'computed', '"00000000000" ;; rut_completo'),
    (104, 'constant', '"" ;; "0"'),
    (105, 'contract', '"" ;; str(contract.analytic_account_id.code)[:20]  # Máximo 20 caracteres'),
]


def field_sources(notes=None):
    """Los 105 `FieldSource`, con las notas de revision que se le pasen."""
    notes = notes or {}
    return [FieldSource(position, kind, source, notes.get(position, ""))
            for position, kind, source in RAW_MATRIX]
