import { useEffect, useRef, useState, type FormEvent } from 'react';
import { dateLabel, fleetRequest, label, type FleetAsset, type FleetContext } from '../services/fleetApi';
import { calendarReminder, type Configuration, type DeviceRegistration } from '../services/fleetConfiguration';
import TrackerSetupGuide from '../components/TrackerSetupGuide';
import TrackerIcon from '../components/TrackerIcon';
const emptyDevice = {imei:'',brand:'Coban',model:'401C',firmware:'',phone:'',operator:'',plan_type:'prepaid',apn:'',responsible:'',last_recharged_on:'',next_recharge_on:'',data_expires_on:'',line_review_on:'',reminder_days:7,notes:''};
function DeviceEditor({device,context,onClose,onSaved}:{device?:DeviceRegistration;context:FleetContext;onClose:()=>void;onSaved:()=>void}) {
 const dialog=useRef<HTMLDialogElement>(null);
 const [form,setForm]=useState({...emptyDevice,...Object.fromEntries(Object.keys(emptyDevice).map(k=>[k, device ? device[k as keyof DeviceRegistration] ?? emptyDevice[k as keyof typeof emptyDevice] : emptyDevice[k as keyof typeof emptyDevice]]))} as typeof emptyDevice);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal();},[]);
 const input=(key:keyof typeof emptyDevice,title:string,type='text',maxLength=100)=><label>{title}<input type={type} maxLength={maxLength} required={['imei','brand','model'].includes(key)} disabled={key==='imei' && !!device} pattern={key==='imei'?'[0-9]{15}':undefined} min={type==='number'?0:undefined} max={type==='number'?90:undefined} value={form[key]} onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>;
 const save=async(e:FormEvent)=>{
  e.preventDefault();if(busy)return;setBusy(true);setError('');
  const payload:Record<string,unknown>={...form};
  for(const key of Object.keys(payload)) if(typeof payload[key]==='string') payload[key]=(payload[key] as string).trim()||null;
  if(device){delete payload.imei;payload.version=device.version;}
  try{await fleetRequest(device?'configuration/devices/'+device.id:'configuration/devices',context,device?'PATCH':'POST',payload);onSaved();}catch(e){setError((e as Error).message);setBusy(false);}
 };
 return <dialog ref={dialog} className="tracker-dialog" aria-labelledby="device-editor-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><form onSubmit={save}><div className="tracker-section-title"><h2 id="device-editor-title">{device?'Gestionar GPS y SIM':'Agregar GPS'}</h2><button type="button" disabled={busy} onClick={onClose} aria-label="Cerrar configuración GPS">×</button></div><p className="fleet-note">Completa la ficha administrativa. Steps configura y verifica el equipo físico. No guardes claves, PIN ni contraseñas aquí.</p><h3>Dispositivo</h3><div className="tracker-form-grid">{input('imei','IMEI (15 dígitos)')}{input('brand','Marca')}{input('model','Modelo')}{input('firmware','Firmware (si lo conoces)')}</div><h3>Conectividad</h3><div className="tracker-form-grid">{input('phone','Número de la SIM','tel',40)}{input('operator','Operador')}<label>Modalidad<select value={form.plan_type} onChange={e=>setForm({...form,plan_type:e.target.value})}><option value="prepaid">Prepago</option><option value="postpaid">Plan mensual</option><option value="iot">Plan IoT / M2M</option><option value="unknown">Por confirmar</option></select></label>{input('apn','APN confirmado por el operador')}{input('responsible','Responsable de las recargas','text',200)}</div><h3>Recordatorios</h3><p className="fleet-note">Fechas manuales según tu operador. No equivalen a una consulta de saldo.</p><div className="tracker-form-grid">{input('last_recharged_on','Última recarga','date')}{input('next_recharge_on','Próxima recarga','date')}{input('data_expires_on','Vencimiento bolsa de datos','date')}{input('line_review_on','Revisar vigencia de la línea','date')}{input('reminder_days','Avisar con días de anticipación','number')}</div><label>Notas de gestión<textarea maxLength={1000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<p role="alert" className="fleet-error">{error}</p>}<div className="tracker-dialog-actions"><button type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="fleet-primary" disabled={busy}>{busy?'Guardando…':'Guardar GPS y SIM'}</button></div></form></dialog>;
}
function AssociationEditor({device,assets,context,onClose,onSaved}:{device:DeviceRegistration;assets:FleetAsset[];context:FleetContext;onClose:()=>void;onSaved:()=>void}) {
 const dialog=useRef<HTMLDialogElement>(null),[asset,setAsset]=useState(device.asset_id||''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{dialog.current?.showModal();},[]);
 const save=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);try{await fleetRequest('configuration/devices/'+device.id+'/assignment',context,'POST',{asset_id:asset||null,reason,version:device.version});onSaved();}catch(e){setError((e as Error).message);setBusy(false);}};
 return <dialog ref={dialog} className="tracker-dialog" aria-labelledby="association-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><form onSubmit={save}><h2 id="association-title">Asociar {device.brand} {device.model}</h2><p>La asociación comienza ahora. El historial anterior permanece en su vehículo original. Confirma con Steps que corresponde a la instalación física.</p><label>Vehículo o equipo<select value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Sin vehículo / desvincular</option>{assets.map(a=><option key={a.asset_id} value={a.asset_id}>{a.name} · {a.plate||'Sin patente'}</option>)}</select></label><label>Motivo de la asociación o cambio<textarea required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p className="fleet-error" role="alert">{error}</p>}<div className="tracker-dialog-actions"><button type="button" disabled={busy} onClick={onClose}>Cancelar</button><button className="fleet-primary" disabled={busy}>{busy?'Guardando…':'Confirmar asociación'}</button></div></form></dialog>;
}
export default function FleetSettings({context,assets,configuration,error,loading,refresh,demo}:{context:FleetContext;assets:FleetAsset[];configuration:Configuration|null;error:string;loading:boolean;refresh:()=>void;demo:boolean}) {
 const [editor,setEditor]=useState<DeviceRegistration|'new'|null>(null),[association,setAssociation]=useState<DeviceRegistration|null>(null),[notice,setNotice]=useState('');
 const saved=()=>{setEditor(null);setAssociation(null);setNotice('Configuración guardada.');refresh();};
 return <div className="tracker-settings">{notice&&<p role="status" className="fleet-notice">{notice}</p>}
 {context.role==='manager' && !demo ? <><div className="tracker-section-title"><div><h2>GPS y conectividad</h2><p>Inventario de tu compañía, asociaciones y continuidad de la SIM.</p></div><button className="fleet-primary" onClick={()=>setEditor('new')}><TrackerIcon name="plus" size={18}/> Agregar GPS</button></div>{error&&<p role="alert" className="fleet-error">{error} <button onClick={refresh}>Reintentar</button></p>}{loading&&<p role="status">Cargando configuración…</p>}{configuration?.reminders.length ? <section className="tracker-reminders"><h2>Recargas y vencimientos por atender</h2>{configuration.reminders.map(r=><button key={r.id} onClick={()=>setEditor(configuration.items.find(d=>d.id===r.registration_id)||null)}><span><strong>{r.title}</strong><small>{r.asset_name||r.device} · {r.responsible||'Sin responsable'}</small></span><b>{r.days_remaining<0?'Venció hace '+Math.abs(r.days_remaining)+' días':r.days_remaining===0?'Hoy':'En '+r.days_remaining+' días'}</b></button>)}<p className="fleet-note">Avisos según las fechas registradas. No confirman saldo ni estado de la línea.</p></section>:null}
 {!loading && configuration && !configuration.items.length && <div className="fleet-empty"><TrackerIcon name="signal" size={34}/><h2>Prepara tu primer GPS</h2><p>Agrega su IMEI y la información de la SIM. Después podrás asociarlo a un vehículo.</p><button onClick={()=>setEditor('new')}>Agregar mi primer GPS</button></div>}
 <div className="tracker-device-grid">{configuration?.items.map(d=><article className="tracker-home-card" key={d.id}><div className="tracker-section-title"><div><span className="fleet-eyebrow">{d.brand}</span><h2>{d.model}</h2></div><TrackerIcon name="signal"/></div><p className="tracker-imei">IMEI {d.imei}</p><h3>{d.asset_name||'Sin vehículo asociado'}</h3><span className={'fleet-state fleet-state--'+d.signal_state}>{label(d.signal_state)}</span><dl className="tracker-device-data"><dt>Última recepción</dt><dd>{dateLabel(d.last_received_at)}</dd><dt>SIM / operador</dt><dd>{d.phone||'Número pendiente'} · {d.operator||'Operador pendiente'}</dd><dt>Responsable</dt><dd>{d.responsible||'Sin asignar'}</dd><dt>Próxima recarga</dt><dd>{d.next_recharge_on||'Sin programar'}</dd><dt>Validación de rastreo</dt><dd>{d.tracking_approved?'Aprobada por Steps':'Pendiente de pruebas técnicas'}</dd></dl><div className="tracker-inline-actions"><button onClick={()=>setEditor(d)}>Gestionar GPS y SIM</button><button onClick={()=>setAssociation(d)}>{d.asset_id?'Cambiar asociación':'Asociar vehículo'}</button>{(d.next_recharge_on||d.data_expires_on||d.line_review_on)&&<button onClick={()=>calendarReminder(d)}>Agregar a calendario</button>}</div></article>)}</div></> : <p className="fleet-notice">{demo?'El inventario GPS y SIM se administra con datos reales fuera de la demostración.':'Tu administrador gestiona los GPS, SIM y asociaciones de esta compañía.'}</p>}
 <TrackerSetupGuide/>{editor&&<DeviceEditor device={editor==='new'?undefined:editor} context={context} onClose={()=>setEditor(null)} onSaved={saved}/>} {association&&<AssociationEditor device={association} assets={assets} context={context} onClose={()=>setAssociation(null)} onSaved={saved}/>}</div>;
}
