import TrackerIcon from '../components/TrackerIcon';
import { label, type FleetAsset, type FleetContext, type FleetFilters } from '../services/fleetApi';
export type TrackerView = 'home' | 'live' | 'fleet' | 'protection' | 'settings';
export default function FleetHome({ assets, context, demo, navigate, onCreate, onImport, onFilter, busy }: {
  assets: FleetAsset[]; context: FleetContext; demo: boolean; navigate: (view: TrackerView) => void;
  onCreate: () => void; onImport: () => void; onFilter: (filters: Partial<FleetFilters>, view?: TrackerView) => void; busy: boolean;
}) {
  const connected = assets.filter(a => a.signal_state === 'received').length;
  const moving = assets.filter(a => a.motion_state === 'moving').length;
  const pending = assets.filter(a => !a.device).length;
  const incidents = assets.filter(a => a.protection_state === 'incident_open').length;
  const types = [...new Set(assets.map(a => a.type))];
  return <div className="tracker-home">
    <section className="tracker-hero">
      <div className="tracker-hero-copy"><span className="tracker-kicker">TU MUNDO EN MOVIMIENTO</span><h1>Cerca de tu flota.<br/><em>Donde sea que vaya.</em></h1><p>Autos, transporte y maquinaria en un mismo lugar. Ubica tus vehículos y organiza la protección de lo que mueve tu empresa.</p><div className="tracker-hero-actions"><button onClick={() => navigate('live')}>Abrir mapa <TrackerIcon name="arrow" size={18}/></button><button className="tracker-hero-secondary" onClick={() => navigate('fleet')}>Administrar flota</button></div><div className="tracker-hero-tags"><span>Autos y particulares</span><span>Transporte</span><span>Maquinaria</span></div></div>
      <div className="tracker-route-art" aria-hidden="true"><svg viewBox="0 0 480 320"><defs><pattern id="route-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0v40" fill="none" stroke="#ffffff" strokeOpacity=".08"/></pattern></defs><rect width="480" height="320" fill="url(#route-grid)"/><path d="M-30 260 120 130 240 230 420 70 510 150M-20 50 100 150 230 30 430 200 510 140" fill="none" stroke="#2d5c51" strokeWidth="26"/><path d="m58 250 100-105 95 75 145-132" fill="none" stroke="#cffa74" strokeWidth="3" strokeDasharray="7 7"/><circle cx="58" cy="250" r="10" fill="#cffa74"/><circle cx="253" cy="220" r="10" fill="#cffa74"/><circle cx="398" cy="88" r="10" fill="#cffa74"/></svg><div className="tracker-art-label tracker-art-label--car"><TrackerIcon name="fleet"/><span>Tu flota<strong>Siempre en contexto</strong></span></div><div className="tracker-art-label tracker-art-label--shield"><TrackerIcon name="protection"/><span>Steps Protección<strong>Alertas y seguimiento</strong></span></div><small>Ilustración del servicio · no representa posiciones reales</small></div>
    </section>
    <section className="tracker-overview" aria-label="Resumen de la compañía">
      {[{ n: assets.length, title: 'Vehículos y equipos', note: 'Tu flota registrada', icon: 'fleet', action: () => onFilter({}) }, { n: connected, title: 'Con señal reciente', note: 'Último dato recibido del GPS', icon: 'signal', action: () => onFilter({signal:'received'}, 'live') }, { n: moving, title: 'En movimiento', note: 'Posición reciente y velocidad', icon: 'live', action: () => onFilter({motion:'moving'}, 'live') }, { n: incidents, title: 'Requieren atención', note: 'Equipos con incidentes abiertos', icon: 'protection', action: () => onFilter({protection:'incident_open'}, 'protection') }].map(item => <button className="tracker-stat" key={item.title} onClick={item.action}><span className="tracker-stat-icon"><TrackerIcon name={item.icon}/></span><strong>{item.n}</strong><span>{item.title}</span><small>{item.note}</small></button>)}
    </section>
    <div className="tracker-home-grid">
      <section className="tracker-home-card"><div className="tracker-section-title"><div><span className="fleet-eyebrow">SIGUIENTE PASO</span><h2>{pending ? 'Conecta tu flota' : assets.length ? 'Todo listo para revisar tu flota' : 'Comienza con tu primer vehículo'}</h2></div><TrackerIcon name="signal"/></div><p>{pending ? `${pending} vehículos o equipos aún no tienen un GPS asociado. Su registro está listo; la instalación y asociación del dispositivo completan la conexión.` : 'Registra autos particulares, vehículos de trabajo o maquinaria. Consulta su posición cuando el GPS esté instalado y asociado.'}</p><ol className="tracker-steps"><li><b>01</b><span>Registra tu vehículo<small>Nombre, patente y responsable.</small></span></li><li><b>02</b><span>Instala y asocia el GPS<small>Coordinación técnica por dispositivo.</small></span></li><li><b>03</b><span>Monitorea y protege<small>Mapa, historial y bandeja de incidentes.</small></span></li></ol>{context.role === 'manager' ? <div className="tracker-inline-actions"><button className="fleet-primary" onClick={onCreate}><TrackerIcon name="plus" size={17}/> Registrar vehículo</button><button disabled={demo || busy} onClick={onImport}>Traer desde Odoo</button><button onClick={() => navigate('settings')}>Configurar GPS y SIM</button></div> : <p className="fleet-note">Tu administrador puede registrar vehículos y coordinar la conexión del GPS.</p>}</section>
      <section className="tracker-home-card"><div className="tracker-section-title"><div><span className="fleet-eyebrow">UNA PLATAFORMA, TODA TU FLOTA</span><h2>Lo que mueve a {context.company}</h2></div></div>{types.length ? <div className="tracker-types">{types.map(type => <button key={type} onClick={() => onFilter({type})}><TrackerIcon name={type === 'tractor' || type === 'machinery' ? 'tractor' : type === 'truck' ? 'truck' : 'fleet'}/><span>{label(type)}</span><strong>{assets.filter(a => a.type === type).length}</strong><TrackerIcon name="arrow" size={16}/></button>)}</div> : <div className="tracker-empty-types"><TrackerIcon name="fleet" size={42}/><p>Aquí verás tu flota, organizada por tipo de vehículo.</p></div>}<div className="tracker-protection-callout"><TrackerIcon name="protection"/><div><h3>Protección con trazabilidad</h3><p>Activa vigilancia digital y gestiona incidentes. La inhibición de arranque requiere equipo, instalación y pruebas aprobadas.</p><button onClick={() => navigate('protection')}>Conocer Protección →</button></div></div></section>
    </div>
  </div>;
}
