from . import hr_route
from . import hr_route_line
from . import product_pricelist_move_item
from . import step_mobilization_registry
from . import step_mobilization_registry_line
from . import step_mobilization_cost_line
from . import step_mobilization_cont_line
from . import step_mobilization_passenger_event
from . import step_mobilization_driver_device
from . import step_mobilization_gps_point
from . import hr_employee
from . import res_partner
from . import fleet_vehicle
from . import product_template
from . import product_pricelist
from . import res_company
from . import res_config_settings
from . import account_move
from . import step_mobilization_contract
from . import step_mobilization_right_to_know
from . import step_mobilization_epp_delivery
from . import step_mobilization_document
from . import step_mobilization_inspection
