# -*- coding: utf-8 -*-
{
    "name": "Steps - Packing",
    "summary": "Packing de campo, recepcion a granel y catalogos de proceso "
                "(puerto desde Studio, ticket 33 Cerro El Plomo).",
    "version": "18.0.1.0.0",
    "category": "Agriculture",
    "author": "Steps Consulting",
    "license": "LGPL-3",
    "depends": ["base", "mail", "step_hr", "product", "mrp", "stock"],
    "data": [
        "security/ir.model.access.csv",
        "views/step_packing_fruit_category_views.xml",
        "views/step_packing_fruit_class_views.xml",
        "views/step_packing_caliber_group_views.xml",
        "views/step_packing_fruit_caliber_views.xml",
        "views/step_packing_process_type_views.xml",
        "views/step_packing_correction_reason_views.xml",
        "views/step_packing_tag_state_views.xml",
        "views/step_packing_tag_type_views.xml",
        "views/step_packing_stop_reason_views.xml",
        "views/step_packing_line_views.xml",
        "views/step_packing_activity_views.xml",
        "views/step_packing_labor_views.xml",
        "views/step_packing_temperature_control_views.xml",
        "views/step_packing_inspection_sag_views.xml",
        "views/step_packing_inspection_usda_views.xml",
        "views/step_packing_fruit_category_tag_views.xml",
        "views/step_packing_fruit_class_tag_views.xml",
        "views/step_packing_caliber_group_tag_views.xml",
        "views/step_packing_fruit_caliber_tag_views.xml",
        "views/step_packing_process_type_tag_views.xml",
        "views/step_packing_correction_reason_tag_views.xml",
        "views/step_packing_tag_state_tag_views.xml",
        "views/step_packing_tag_type_tag_views.xml",
        "views/step_packing_stop_reason_tag_views.xml",
        "views/step_packing_line_tag_views.xml",
        "views/step_packing_activity_tag_views.xml",
        "views/step_packing_campo_tag_views.xml",
        "views/step_packing_reception_tag_views.xml",
        "views/step_packing_campo_stage_views.xml",
        "views/step_packing_reception_stage_views.xml",
        "views/step_packing_campo_views.xml",
        "views/step_packing_reception_views.xml",
        "views/menu.xml",
    ],
    "application": True,
    "installable": True,
}
