# -*- coding: utf-8 -*-
{
    'name': "Steps Maquinaria",
    'summary': "Uso, costeo estándar, contabilización y conciliación de maquinaria agrícola",
    'description': """Control integral de maquinaria agrícola: horas, OT-BPA,
costeo por ocho conceptos, distribución analítica y conciliación real versus estándar.""",
    'author': "Steps App",
    'website': "https://stepsapp.cl",
    'category': 'Operations/Agriculture',
    'version': '18.0.22.0.0',

    'depends': ['base',
                'hr',
                'step_hr',
                'product',
                'account',
                'fleet'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'wizard/report_machinery_wizard_view.xml',
        'wizard/real_cost_machinery_wizard.xml',
        'views/type_costing_machinery_view.xml',
        'views/type_service_machinery_view.xml',
        'views/step_machinery_tracking_view.xml',
        'views/step_hrs_machinery_view.xml',
        'views/real_cost_machinery_view.xml',
        'views/step_cost_machinery_view.xml',
        'views/step_machinery_implement_view.xml',
        'views/product_template_view.xml',
        'views/step_labor_views.xml',
        'views/hr_employee_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu_views.xml',
    ],
    'demo': [],
    'post_init_hook': 'post_init_canonical_catalog',
    'application': True,
    'license': 'LGPL-3',
}
