"""Matriz campo Previred -> dato del motor Blueminds (l10n_cl_hr).

**Generada desde el codigo del generador vigente**, no deducida: cada entrada
guarda la expresion exacta de `wizard.export.csv.previred.action_generate_csv` que produce ese campo.

Es la evidencia de que ninguna correspondencia entre regla salarial y campo
oficial se adivino, y el punto de partida para conciliar importes contra
muestras existentes. Si el proveedor cambia su generador, esta matriz debe
regenerarse y las pruebas de conciliacion lo detectan.
"""

from odoo.addons.step_hr_previred.models.previred_adapter import FieldSource

#: `(posicion, tipo de origen, expresion del generador)`
RAW_MATRIX = [

    (1, 'computed', 'self._acortar_str(rut, 11)'),
    (2, 'computed', 'self._acortar_str(rut_dv, 1)'),
    (3, 'employee', 'self._arregla_str(payslip.employee_id.last_name.upper(), 30) if payslip.employee_id.last_name else ""'),
    (4, 'employee', 'self._arregla_str(payslip.employee_id.mothers_name.upper(), 30) if payslip.employee_id.mothers_name else ""'),
    (5, 'employee', '"%s %s" % (self._arregla_str(payslip.employee_id.firstname.upper(), 15), self._arregla_str(payslip.employee_id.middle_name.upper(), 15) if payslip.employee_id.middle_name else \'\')'),
    (6, 'employee', 'sexo_data.get(payslip.employee_id.gender, "") if payslip.employee_id.gender else ""'),
    (7, 'employee', 'self.get_nacionalidad(payslip.employee_id.country_id.id)'),
    (8, 'computed', 'self.get_tipo_pago(payslip.employee_id)'),
    (9, 'period', 'date_start_format'),
    (10, 'period', 'date_stop_format'),
    (11, 'computed', 'self.get_regimen_provisional(payslip.contract_id)'),
    (12, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (13, 'computed', 'int(self.get_dias_trabajados(payslip and payslip[0] or False))'),
    (14, 'computed', 'self.get_tipo_linea(payslip and payslip[0] or False)'),
    (15, 'computed', 'payslip.movimientos_personal'),
    (16, 'computed', 'payslip.date_from.strftime("%d/%m/%Y") if payslip.movimientos_personal != \'0\' else \'00/00/0000\''),
    (17, 'computed', 'payslip.date_to.strftime("%d/%m/%Y") if payslip.movimientos_personal != \'0\' else \'00/00/0000\''),
    (18, 'rule', "self.get_tramo_asignacion_familiar(payslip, self.get_payslip_lines_value_2(payslip,'TOTIM'))"),
    (19, 'contract', 'payslip.contract_id.carga_familiar'),
    (20, 'contract', 'payslip.contract_id.carga_familiar_maternal'),
    (21, 'contract', 'payslip.contract_id.carga_familiar_invalida'),
    (22, 'rule', 'int(self.get_payslip_lines_value_2(payslip, \'ASIGFAM\') if self.get_payslip_lines_value_2(payslip,\'ASIGFAM\') else "0")'),
    (23, 'rule', 'int(self.get_payslip_lines_value_2(payslip, \'ASIGFARET\') if self.get_payslip_lines_value_2(payslip,\'ASIGFARET\') else "0")'),
    (24, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (25, 'constant', '"N"'),
    (26, 'contract', 'payslip.contract_id.afp_id.codigo if payslip.contract_id.afp_id.codigo else "0"'),
    (27, 'rule', "int(self.get_imponible_afp_2(payslip and payslip[0] or False, self.get_payslip_lines_value_2(payslip,'TOTIM'), self.get_payslip_lines_value_2(payslip,'IMPLIC')))"),
    (28, 'rule', "int(self.get_payslip_lines_value_2(payslip,'PREV') + self.get_payslip_lines_value_2(payslip,'PREVADD'))"),
    (29, 'rule', "int(self.get_payslip_lines_value_2(payslip,'SIS'))"),
    (30, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (31, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (32, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (33, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (34, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (35, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (36, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (37, 'unused', 'en blanco (uso futuro / no aplica)'),
    (38, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (39, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (40, 'rule', 'payslip.contract_id.apv_id.codigo if self.get_payslip_lines_value_2(payslip,\'APV\') else "0"'),
    (41, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (42, 'rule', 'payslip.contract_id.forma_pago_apv if self.get_payslip_lines_value_2(payslip,\'APV\') else "0"'),
    (43, 'rule', 'int(self.get_payslip_lines_value_2(payslip,\'APV\')) if self.get_payslip_lines_value_2(payslip,\'APV\') else "0"'),
    (44, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (45, 'unused', 'en blanco (uso futuro / no aplica)'),
    (46, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (47, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (48, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (49, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (50, 'unused', 'en blanco (uso futuro / no aplica)'),
    (51, 'unused', 'en blanco (uso futuro / no aplica)'),
    (52, 'unused', 'en blanco (uso futuro / no aplica)'),
    (53, 'unused', 'en blanco (uso futuro / no aplica)'),
    (54, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (55, 'constant', '"00"'),
    (56, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (57, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (58, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (59, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (60, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (61, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (62, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (63, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (64, 'rule', "int(self.get_imponible_afp_2(payslip and payslip[0] or False, self.get_payslip_lines_value_2(payslip,'TOTIM'), self.get_payslip_lines_value_2(payslip,'IMPLIC'))) if payslip.contract_id.isapre_id.codig"),
    (65, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (66, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (67, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (68, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (69, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (70, 'rule', 'int(self.get_payslip_lines_value_2(payslip,\'FONASA\') if payslip.contract_id.isapre_id.codigo==\'07\' else "0")'),
    (71, 'rule', 'int(self.get_payslip_lines_value_2(payslip,\'ISL\')) if self.get_payslip_lines_value_2(payslip,\'ISL\') else "0"'),
    (72, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (73, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (74, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (75, 'contract', 'payslip.contract_id.isapre_id.codigo'),
    (76, 'constant', '" " if payslip.contract_id.isapre_id.codigo==\'07\' else payslip.contract_id.isapre_fun if payslip.contract_id.isapre_fun else ""'),
    (77, 'rule', '"0" if payslip.contract_id.isapre_id.codigo==\'07\' else self.get_imponible_salud(payslip and payslip[0] or False, self.get_payslip_lines_value_2(payslip,\'TOTIM\'))'),
    (78, 'constant', '"1" if payslip.contract_id.isapre_id.codigo==\'07\' else "2"'),
    (79, 'contract', '"0" if payslip.contract_id.isapre_id.codigo==\'07\' else payslip.contract_id.isapre_cotizacion_uf'),
    (80, 'rule', '"0" if payslip.contract_id.isapre_id.codigo==\'07\' else int(self.get_payslip_lines_value_2(payslip,\'SALUD\'))'),
    (81, 'rule', '"0" if payslip.contract_id.isapre_id.codigo==\'07\' else int(self.get_payslip_lines_value_2(payslip,\'ADISA\'))'),
    (82, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (83, 'indicator', 'payslip.indicadores_id.ccaf_id.codigo if payslip.indicadores_id.ccaf_id.codigo else "00"'),
    (84, 'rule', "int(self.get_imponible_afp(payslip and payslip[0] or False, self.get_payslip_lines_value_2(payslip,'TOTIM'))) if (self.get_dias_trabajados(payslip and payslip[0] or False)>0) and payslip.contract_id.i"),
    (85, 'rule', 'int(self.get_payslip_lines_value_2(payslip,\'PCCAF\') if self.get_payslip_lines_value_2(payslip,\'PCCAF\') else "0")'),
    (86, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (87, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (88, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (89, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (90, 'computed', 'field_90'),
    (91, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (92, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (93, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (94, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (95, 'unused', 'en blanco (uso futuro / no aplica)'),
    (96, 'indicator', 'payslip.indicadores_id.mutualidad_id.codigo if payslip.indicadores_id.mutualidad_id.codigo else "00"'),
    (97, 'rule', "self.get_imponible_mutual(payslip and payslip[0] or False, self.get_payslip_lines_value_2(payslip,'TOTIM'))"),
    (98, 'rule', 'int(self.get_payslip_lines_value_2(payslip,\'MUT\')) if self.get_payslip_lines_value_2(payslip,\'MUT\') else "0"'),
    (99, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (100, 'rule', "self.get_imponible_seguro_cesantia(payslip and payslip[0] or False, self.get_payslip_lines_value_2(payslip,'TOTIM') , self.get_payslip_lines_value_2(payslip,'IMPLIC'))"),
    (101, 'rule', 'int(self.get_payslip_lines_value_2(payslip,\'SECE\')) if self.get_payslip_lines_value_2(payslip,\'SECE\') else "0"'),
    (102, 'rule', 'int(self.get_payslip_lines_value_2(payslip,\'SECEEMP\')) if self.get_payslip_lines_value_2(payslip,\'SECEEMP\') else "0"'),
    (103, 'unused', '"0" (uso futuro / no aplica en este motor)'),
    (104, 'unused', 'en blanco (uso futuro / no aplica)'),
    (105, 'contract', "payslip.contract_id.analytic_account_id.name or ''"),
]


def field_sources(notes=None):
    """Los 105 `FieldSource`, con las notas de revision que se le pasen."""
    notes = notes or {}
    return [FieldSource(position, kind, source, notes.get(position, ""))
            for position, kind, source in RAW_MATRIX]
